import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { z } from 'zod';
import { getDatabase } from '@/db/client';
import { geographyLevels, parentLevelOf, validateHierarchy } from '@/domain/geography';
import { logger } from '@/lib/logger';

/**
 * Geography registry importer (ADR-0003, ADR-0005).
 *
 * Reads the registry produced by scripts/build-geometry.ts and upserts it. The
 * registry is a committed artefact, so this import is reproducible without
 * re-downloading 70 MB of boundary archives, and it is deterministic: the same
 * file always produces the same rows.
 *
 * Idempotent by upsert on (code, level, edition). Running it twice changes
 * nothing.
 *
 * Import order follows the hierarchy, because a child cannot resolve its parent
 * before the parent exists.
 */

const SOURCE_KEY = 'abs-asgs';
const DATASET = 'ASGS boundaries';

/**
 * External data is validated before it becomes a domain object (ADR-0008).
 * The registry is generated by this project, but it is generated from a
 * third-party release whose schema can change between editions.
 */
const entrySchema = z.object({
  code: z.string().min(1),
  name: z.string().min(1),
  level: z.enum(geographyLevels),
  parentCode: z.string().min(1).nullable(),
  hasGeometry: z.boolean(),
  areaSqKm: z.number().nonnegative().nullable(),
});

const registrySchema = z.array(entrySchema).min(1);

export type RegistryEntry = z.infer<typeof entrySchema>;

export interface ImportOutcome {
  readonly runId: string;
  readonly seen: number;
  readonly written: number;
  readonly skipped: number;
  readonly quarantined: number;
}

export function registryPath(edition: string): string {
  return join('data', 'geography', `registry-${edition}.json`);
}

/** Import order: parents before children. */
const LEVEL_ORDER = ['COUNTRY', 'STATE', 'SA4'] as const;

export async function importGeography(edition: string): Promise<ImportOutcome> {
  const database = getDatabase();
  if (!database.ok) {
    throw new Error(`Cannot import geography: ${database.error.message}`);
  }
  const prisma = database.value;

  const source = await prisma.source.findUnique({ where: { key: SOURCE_KEY } });
  if (!source) {
    throw new Error(
      `Source "${SOURCE_KEY}" is not registered. Run the seed before importing.`,
    );
  }

  // A source that is not permitted must not be imported, whatever the caller
  // intended. Compliance is checked here rather than trusted (ADR-0009).
  if (source.complianceStatus !== 'VERIFIED') {
    throw new Error(
      `Source "${SOURCE_KEY}" has compliance status ${source.complianceStatus}. ` +
        'Verify its terms before importing. See docs/compliance/SOURCE_REGISTER.md',
    );
  }

  const raw: unknown = JSON.parse(await readFile(registryPath(edition), 'utf8'));
  const parsed = registrySchema.safeParse(raw);
  if (!parsed.success) {
    throw new Error(
      `Registry for ${edition} failed validation: ${parsed.error.issues
        .slice(0, 5)
        .map((issue) => `${issue.path.join('.')}: ${issue.message}`)
        .join('; ')}`,
    );
  }
  const entries = parsed.data;

  // Structural validation before any write. Importing a broken hierarchy would
  // leave orphaned areas that only surface as holes in the map much later.
  const problems = validateHierarchy(entries);
  if (problems.length > 0) {
    throw new Error(
      `Registry for ${edition} has ${problems.length} hierarchy problem(s), nothing imported:\n` +
        problems
          .slice(0, 10)
          .map((p) => `  - ${p.level} ${p.code}: ${p.problem}`)
          .join('\n'),
    );
  }

  const run = await prisma.ingestionRun.create({
    data: {
      sourceKey: SOURCE_KEY,
      dataset: DATASET,
      status: 'RUNNING',
      triggeredBy: 'manual',
    },
  });

  let written = 0;
  let quarantined = 0;
  // Nothing is skipped yet. The registry is small and fully upserted every run;
  // content-hash skipping belongs with the larger job feeds (ADR-0005).
  const skipped = 0;

  try {
    // (level, code) to id, so a child resolves its parent without another
    // query. Keyed by level as well as code because ASGS codes repeat across
    // levels: "ZZZ" is both a COUNTRY and an SA4.
    const idByLevelAndCode = new Map<string, string>();

    for (const level of LEVEL_ORDER) {
      for (const entry of entries.filter((candidate) => candidate.level === level)) {
        const parentLevel = parentLevelOf(entry.level);
        const parentId =
          entry.parentCode === null || parentLevel === null
            ? null
            : (idByLevelAndCode.get(`${parentLevel}:${entry.parentCode}`) ?? null);

        if (entry.parentCode !== null && parentId === null) {
          // Should be unreachable: validateHierarchy already checked this.
          // Quarantined rather than thrown so one bad record cannot abort a run.
          await prisma.ingestionError.create({
            data: {
              runId: run.id,
              sourceKey: SOURCE_KEY,
              sourceId: entry.code,
              kind: 'MAPPING',
              message: `Parent "${entry.parentCode}" was not imported before its child.`,
              rawPayload: entry,
            },
          });
          quarantined += 1;
          continue;
        }

        const data = {
          name: entry.name,
          level: entry.level,
          hasGeometry: entry.hasGeometry,
          areaSqKm: entry.areaSqKm,
          parentId,
          sourceKey: SOURCE_KEY,
        };

        const row = await prisma.geography.upsert({
          where: {
            code_level_asgsEdition: {
              code: entry.code,
              level: entry.level,
              asgsEdition: edition,
            },
          },
          create: { code: entry.code, asgsEdition: edition, ...data },
          update: data,
        });

        idByLevelAndCode.set(`${entry.level}:${entry.code}`, row.id);
        written += 1;
      }
    }

    await prisma.ingestionRun.update({
      where: { id: run.id },
      data: {
        status: 'COMPLETED',
        finishedAt: new Date(),
        recordsSeen: entries.length,
        recordsWritten: written,
        recordsSkipped: skipped,
        recordsQuarantined: quarantined,
      },
    });
  } catch (error) {
    await prisma.ingestionRun.update({
      where: { id: run.id },
      data: {
        status: 'FAILED',
        finishedAt: new Date(),
        recordsSeen: entries.length,
        recordsWritten: written,
        recordsQuarantined: quarantined,
        // Redacted by the logger's rules when logged; stored as a plain summary.
        error: error instanceof Error ? error.message : String(error),
      },
    });
    throw error;
  }

  logger.info('Geography import complete', {
    edition,
    written,
    skipped,
    quarantined,
  });

  return { runId: run.id, seen: entries.length, written, skipped, quarantined };
}
