import type { SourceDescriptor } from '@/domain/source';

/**
 * The source registry.
 *
 * This is the single source of truth for which sources exist and what state
 * they are in. The database mirrors it via the seed, and a test asserts the two
 * agree, so an operator reading the admin view and a developer reading the code
 * cannot see different answers.
 *
 * Keep this in step with docs/compliance/SOURCE_REGISTER.md, which records the
 * evidence behind each status. This file records the status; that document
 * records why.
 *
 * Nothing here is marked VERIFIED yet. No licence has been read.
 */
export const sourceDescriptors: readonly SourceDescriptor[] = [
  {
    key: 'jsa-ivi',
    displayName: 'Jobs and Skills Australia',
    kind: 'MARKET_INDICATOR',
    activation: 'ACTIVE',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: true,
    notes:
      'Internet Vacancy Index. Designated the active market intelligence source and ' +
      'the only source of public value at launch, so licence verification blocks ' +
      'production rather than a feature. Counts online job advertisements on a ' +
      'defined set of boards; never described as total Australian vacancies.',
  },
  {
    key: 'abs-asgs',
    displayName: 'Australian Bureau of Statistics',
    kind: 'GEOGRAPHY',
    activation: 'ACTIVE',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: true,
    notes:
      'Australian Statistical Geography Standard boundaries. Licence not yet ' +
      'confirmed for the release the product will use. No boundary file is ' +
      'committed before confirmation.',
  },
  {
    key: 'anzsco',
    displayName: 'Australian Bureau of Statistics',
    kind: 'CLASSIFICATION',
    activation: 'PENDING',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: true,
    notes:
      'ANZSCO occupation classification. Version to standardise on is not yet ' +
      'decided. Occupation mappings are never invented; an unmapped listing stays ' +
      'unmapped.',
  },
  {
    key: 'adzuna',
    displayName: 'Adzuna',
    kind: 'JOB_LISTING',
    activation: 'BLOCKED',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: true,
    notes:
      'Onboarding requires organization and website details that do not exist yet. ' +
      'These are never invented and onboarding is never bypassed. The adapter is ' +
      'built without live credentials.',
  },
  {
    key: 'synthetic',
    displayName: 'Development fixtures',
    kind: 'JOB_LISTING',
    activation: 'DEVELOPMENT_ONLY',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: false,
    notes:
      'Generated by this project. Describes no real employer, vacancy, salary or ' +
      'person. Never in production: the process refuses to start if it is enabled ' +
      'there. Never labelled as a real provider.',
  },
];

export function findSourceDescriptor(key: string): SourceDescriptor | undefined {
  return sourceDescriptors.find((descriptor) => descriptor.key === key);
}
