import type { SourceDescriptor } from '@/domain/source';

/**
 * The source registry.
 *
 * This is the single source of truth for which sources exist and what state
 * they are in. The database mirrors it via the seed, and a test asserts the two
 * agree, so an operator reading the admin view and a developer reading the code
 * cannot see different answers.
 *
 * Keep this in step with docs/compliance/SOURCE_REGISTER.md, which records the
 * evidence behind each status. This file records the status; that document
 * records why.
 *
 * Nothing here is marked VERIFIED yet. No licence has been read.
 */
export const sourceDescriptors: readonly SourceDescriptor[] = [
  {
    key: 'jsa-ivi',
    displayName: 'Jobs and Skills Australia',
    kind: 'MARKET_INDICATOR',
    activation: 'ACTIVE',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: true,
    notes:
      'Internet Vacancy Index. Designated the active market intelligence source and ' +
      'the only source of public value at launch, so licence verification blocks ' +
      'production rather than a feature. Counts online job advertisements on a ' +
      'defined set of boards; never described as total Australian vacancies.',
  },
  {
    key: 'abs-asgs',
    displayName: 'Australian Bureau of Statistics',
    kind: 'GEOGRAPHY',
    activation: 'ACTIVE',
    complianceStatus: 'VERIFIED',
    attributionRequired: true,
    // CC BY 4.0 requires attribution, a licence notice, a link to the licence,
    // and an indication that changes were made. The product simplifies geometry
    // for display (ADR-0003), so the change indication is mandatory. Stored
    // verbatim: the UI renders this string and must not paraphrase it.
    attributionText:
      'Based on Australian Bureau of Statistics data. Australian Statistical ' +
      'Geography Standard (ASGS) Edition 4, July 2026 to June 2031. ' +
      '© Commonwealth of Australia, administered by the ABS, licensed under ' +
      'CC BY 4.0. Boundaries have been simplified for display.',
    termsUrl: 'https://creativecommons.org/licenses/by/4.0/',
    homepageUrl:
      'https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs/edition-4-july-2026-june-2031/access-and-downloads/digital-boundary-files',
    notes:
      'Australian Statistical Geography Standard boundaries. Verified 2026-08-28 ' +
      'as CC BY 4.0: commercial use, redistribution and adaptation all permitted ' +
      'with attribution. Edition 4 Main Structure (SA4, State, Australia) was ' +
      'released 22 July 2026 on the GDA2020 datum. The Coat of Arms, ABS logo and ' +
      'trade marks are excluded from the licence and are never used. Which ASGS ' +
      'edition JSA IVI reports against is still open; see the source register.',
  },
  {
    key: 'anzsco',
    displayName: 'Australian Bureau of Statistics',
    kind: 'CLASSIFICATION',
    activation: 'PENDING',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: true,
    notes:
      'ANZSCO occupation classification. Version to standardise on is not yet ' +
      'decided. Occupation mappings are never invented; an unmapped listing stays ' +
      'unmapped.',
  },
  {
    key: 'adzuna',
    displayName: 'Adzuna',
    kind: 'JOB_LISTING',
    activation: 'BLOCKED',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: true,
    notes:
      'Onboarding requires organization and website details that do not exist yet. ' +
      'These are never invented and onboarding is never bypassed. The adapter is ' +
      'built without live credentials.',
  },
  {
    key: 'synthetic',
    displayName: 'Development fixtures',
    kind: 'JOB_LISTING',
    activation: 'DEVELOPMENT_ONLY',
    complianceStatus: 'UNVERIFIED',
    attributionRequired: false,
    notes:
      'Generated by this project. Describes no real employer, vacancy, salary or ' +
      'person. Never in production: the process refuses to start if it is enabled ' +
      'there. Never labelled as a real provider.',
  },
];

export function findSourceDescriptor(key: string): SourceDescriptor | undefined {
  return sourceDescriptors.find((descriptor) => descriptor.key === key);
}
